baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
[taxonomies]
  tag = "tags"
[outputs]
  section = ["JSON"]
  page = ["JSON"]
  home = ["JSON"]

publishDir = "docs"
