baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
[taxonomies]
  tag = "tags"
[outputs]
  page = ["html", "json"]
  section = ["html", "json"]
  home = ["json"]
